name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Generate snake animation
        uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: Hiran-Abhisheka
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Show build status
        run: git status

      - name: Push generated files to output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
