name: Test Basic Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: |
          echo "Testing if GitHub Actions work"
          echo "Current date: $(date)"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
